### ISSUE TITLE
探讨

### ISSUE THREAD

**Issue by tensions** [tokenIsme/quant4j#2]
发现几个问题
1. 当机器人异常的时候，比如下单异常的时候，会一直循环, 点击停止机器人是停止不了的，只能手动停服务,   建议增加一个强制kill功能
2. 能否运行通用策略呢，例如JAVASCRIPT策略，类似于botvs 这种架构,

**Comment by tokenIsme** [comment]
1 异常后捕获异常 处理下就行了    2代码实现了 下单 获取余额等等的方法 用js去调用这些方法 我暂时没时间弄这个  有空加上这个  botvs 这种已经很成熟了 弄一样的 没意思啊
